language: node_js
node_js:
  - "iojs"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

# Make sure we have new NPM.
before_install:
  - npm install -g npm

before_script:
  - npm install -g grunt-cli

script:
  - grunt
